### ISSUE TITLE
503 on attempt to download

### ISSUE THREAD

**Issue by cdilga** [ethanfann/slackmojis-downloader#11]
OS: Windows 10
Shell: Powershell

Steps:
```ps
git clone https://github.com/ethanfann/slackmojis-downloader
cd slackmojis-downloader
npm install
npm start
```

After running npm start, the following is output:
```ps
PS C:\Users\Chris\Documents\dev\slackmojis-downloader> npm start

> slackmojis_downloader@2.0.0 start C:\Users\Chris\Documents\dev\slackmojis-downloader
> node cli.js

⠼ Requesting Emoji Listing
Error: Request failed with status code 503
    at createError (C:\Users\Chris\Documents\dev\slackmojis-downloader\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Chris\Documents\dev\slackmojis-downloader\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Chris\Documents\dev\slackmojis-downloader\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! slackmojis_downloader@2.0.0 start: `node cli.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the slackmojis_downloader@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chris\AppData\Roaming\npm-cache\_logs\2021-03-05T09_10_33_729Z-debug.log
```

Expected behaviour:
It downloads the emoji

**Comment by ethanfann** [comment]
Greetings! I took a look into this and, unfortunately, it seems their server isn't able to produce the listing of emojis required for the downloader to function.

You can verify this by navigating to https://slackmojis.com/emojis.json which results in an error from Heroku.

I'll add a more helpful message for when this situation occurs and hopefully Slackmojis can implement pagination so this operation isn't so resource intensive for them.

**Comment by ethanfann** [comment]
I've been evaluating this periodically over the last two weeks and it's been hit or miss. A couple times the retrieval of emojis.json will work and others it's just timed out. 

I'm continuing to look into the situation.

**Comment by ragebiswas** [comment]
Thanks for this tool @ethanfann . I'm facing the same problem. One suggestion I have here is - for folks trying out this tool, it would be better to start with a cached/stale version of `emojis.json` from the repo if it fails to download.

**Comment by ankur-lt** [comment]
Any update here @ethanfann ? I am trying since few weeks but accessing  emojis.json gives 503

**Comment by jkupferman** [comment]
Hi folks, Slackmojis creator here. 

It turns out that having a single API call return 40k+ emojis at once may not have been the best idea 😬 . The combination of generating a ton of json objects + garbage collection was causing the request to timeout. 

The good news is I've fixed this by introducing pagination. https://slackmojis.com/emojis.json?page=0 now returns the first 500 emojis, then one can keep incrementing the the page number until it returns an empty array, signaling the end. Right now there are ~40 pages. 

This is live as of yesterday, which I believe means any folks using this app will only get the first 500 emojis. Sorry about that, should have given folks more of a heads up. 

Once you get pagination added this downloader should be a lot more stable and consistent.

Cheers and great work on this.

**Comment by ethanfann** [comment]
Greatly appreciate the work you've been doing @jkupferman. I'll add support for pagination in the coming days.

**Comment by ethanfann** [comment]
First pass at support for the new paginated API is live. Ideally I'd like to move towards a setup that incrementally downloads as pages are being retrieved, but I am happy enough with how it is now to let people start trying it out.

Once retrieved it seems like I'm obtaining 120-140 emojis/s with the total set taking around 5 minutes to download. Results may vary depending on system, of course.

![image](https://user-images.githubusercontent.com/6005240/122855226-c2006f80-d2c9-11eb-8d8b-eae84c9d1e0d.png)
